### ISSUE TITLE
Change the EFY UI customization button icon from a generic hamburger menu to a more descriptive icon to improve UX

### ISSUE THREAD

**Issue by codenyte** [dragos-efy/efy#11]
The icon on the button that opens the UI customization button is just a generic hamburger menu, that may cause confusion for some users as it might be interpreted as some kind of sidebar for the website, not as a theme customization menu.

Current design:
![image](https://github.com/dragos-efy/efy/assets/39193783/3462d71a-b49f-4547-bfe1-965b17ee2b4a)
![image](https://github.com/dragos-efy/efy/assets/39193783/f93bde0a-7f7b-4af5-a207-71c020b94d6b)

Therefore, I suggest using a different icon. I don't know how icons are handled in EFY, but I found the `palette` icon on Font Awesome: https://fontawesome.com/icons/palette?f=classic&s=solid

It would be better from a UX perspective, because it is much more descriptive than the generic hamburger menu.

**Comment by dragos-efy** [comment]
It's a generic icon on purpose, because in terms of UX you likely want users to use 1 menu for everything, rather than 1 for design and 1 for the app settings. And the efy menu allows devs to add their own navigation links at the top of it as well as their own components, html etc.

However, yes, the efy menu can work isolated too, which is the default behavior, to add a floating button if the app doesn't integrate its own menu with efy. Also, apps are not tied to using that icon, they can make every html element trigger the efy menu to open / close if they use the `efy_sidebar_btn` attribute and use any icons they want.

You have a point tho, cuz some people don't know about efy until they open the menu, so I had some people not realizing they can do all the crazy cool stuff efy allows them to until someone told them or they opened the menu. My idea is to maybe add a small thing next to it the first time they open the app that says something like `Open this menu to customize the app` maybe. I'm not sure yet what solutions are best, but yeah, the icon or type of element that triggers the menu is already customizable. You can even add 40 of those buttons, all different if you want lol. Thanks for the feedback, lmk if you have more!
