### ISSUE TITLE
disable Efy UI option

### ISSUE THREAD

**Issue by luca-e075e** [dragos-efy/efy#3]
Hi,
end users should have the possibility to completely disable Efy UI, since as far as I understand it is a customized UI version on top of a working one. A switch button could be integrated near EFY UI logo like this

![efy ui](https://user-images.githubusercontent.com/15078341/196668716-b4cb74e9-a6c9-4da5-a112-ad1f65543e45.png)

Thanks
Luca

**Comment by dragos-efy** [comment]
I'm not sure if you mean in general or for piped, so I'll answer for both.

For Piped it's not on top really, cuz quite a substantial amount of code has been replaced to have a better integration and more speed. Making a "no efy toggle" means supporting 2 different versions of Piped at once, which would probably not be efficient for users because of extra code needing to be downloaded, although dynamically.

In general, efy can be added to a html page let's say, with no framework and it should look decent by default. So in a sense it's on top, you throw it at some page and it should be fine, but then if the page using it relies on it for styling, disabling efy would sorta be equal to just disabling all styling... so the user can just disable js / css.

I get your idea I think, but I'm not sure if it makes sense practically, because then I'd need to make sure that all the code doesn't work except for a toggle... The sidebar from your screenshot is efy as well... so without efy the sidebar is gone. Makes sense? Like it's either there or not... Making it be there just for the toggle can be done, but that would mean extra code and conditions or using a different file just for the toggle to not load an entire file that won't be used.

If you have better ideas and use cases that would make sense practically, feel free to share them. But a toggle in the efy sidebar menu can't work, because there's no sidebar without efy. Thanks for the feedback!
