### ISSUE TITLE
efy ui settings icon button is too generic

### ISSUE THREAD

**Issue by luca-e075e** [dragos-efy/efy#4]
Hi,
the icon used to access Efy UI setting is too generic since the same is used by some sites.

1. open a mobile browser (such as firefox)
2. go to https://piped.mha.fi

As you can see, there are two "3 lines button" that are nearly the same except minor colour differences. The top one is for piped's settings, meanwhile the middle one is for Efy UI settings

Thanks
Luca

![Screenshot_2022-10-19-12-41-22-34](https://user-images.githubusercontent.com/15078341/196670048-2d198a80-b773-423c-a54a-5e6377a344ac.jpg)

**Comment by dragos-efy** [comment]
It's generic on purpose, because this can be used as a main app menu as well by apps / sites, not just for customising the app. Btw I made the icons the same on Piped myself so I'm aware haha, I didn't get to make it more consistent and intuitive YET.

I already am working on a a modular solution for this because tackling it is harder than it seems at first UX wise, and I want the user to be able to decide where the button is and what state the button is in... floating, hidden, absolute etc. But it will take a bit of time, because I need to find a job, I got lots of things to work on etc.

efy is still in beta, we haven't released it on the official Piped instance yet, so although it might look quite stable, some things are still quirky, which is why I was surprised it went live on the mha.fi instance, cuz it's not fully stable and ready for the average user, although close to it.

Thanks for the feedback! Keep it going if you have more to share, or you can dm me on matrix or join the efy matrix room.
